# CH02-01 연습문제 — 데이터 분석 개요와 NumPy·Pandas 기초

**총 문제 수**: 30문제 (기본 25 + 심화 5)  
**범위**: 데이터 분석 개요 / NumPy 기초 / Pandas 기초 / ndarray 심화 / 벡터 연산

| Part | 주제 | 문제 |
|---|---|---|
| 1 | Part 1. 데이터 분석 개요 | 문제 1~5 |
| 2 | Part 2. NumPy 기초 | 문제 6~15 |
| 3 | Part 3. Pandas 기초 | 문제 16~25 |
| 4 | Part 4. ⭐ 심화: ndarray 심화 | 문제 26~28 |
| 5 | Part 5. ⭐ 심화: 벡터 연산 | 문제 29~30 |


---
## Part 1. 데이터 분석 개요


### 문제 1. (초급) 데이터 분석 흐름 정리

**학습목표**  
데이터 분석의 기본 흐름을 순서대로 이해한다.

**문제**  
아래 단계들을 데이터 분석 흐름에 맞게 리스트로 저장하고 출력하세요: 문제 정의, 데이터 수집, 데이터 정제, 탐색적 분석, 모델링, 결과 해석

**힌트**  
문자열 6개를 리스트에 담고 `print()`로 출력하세요.

In [1]:
# 데이터 분석 흐름을 리스트로 저장하세요.
steps = ["문제 정의", "데이터 수집", "데이터 정제", "탐색적 분석", "모델링", "결과 해석"]

# 결과를 출력하세요.
print(steps)

['문제 정의', '데이터 수집', '데이터 정제', '탐색적 분석', '모델링', '결과 해석']


### 문제 2. (초급) 정형 데이터와 비정형 데이터 구분

**학습목표**  
데이터 유형을 정형/비정형으로 구분한다.

**문제**  
아래 데이터 예시를 정형 데이터와 비정형 데이터로 나누어 각각 리스트에 저장하세요.
예시: 매출 CSV, 고객 테이블, 뉴스 기사, 이미지, 음성 파일, 설문 엑셀

**힌트**  
표 형태로 정리 가능한 데이터는 정형 데이터, 자유로운 형태의 데이터는 비정형 데이터입니다.

In [2]:
structured = ["매출 CSV", "고객 테이블", "설문 엑셀"]
unstructured = ["뉴스 기사", "이미지", "음성파일"]

print('정형 데이터:', structured)
print('비정형 데이터:', unstructured)

정형 데이터: ['매출 CSV', '고객 테이블', '설문 엑셀']
비정형 데이터: ['뉴스 기사', '이미지', '음성파일']


### 문제 3. (초급) 라이브러리 import

**학습목표**  
데이터 분석에서 자주 사용하는 라이브러리를 불러온다.

**문제**  
NumPy와 Pandas를 각각 `np`, `pd`라는 별칭으로 import하세요.

**힌트**  
`import 라이브러리 as 별칭` 형식을 사용합니다.

In [3]:
# NumPy와 Pandas를 import하세요.
import numpy as np
import pandas as pd

print('import 완료')

import 완료


### 문제 4. (초급) 데이터셋을 표 형태로 생각하기

**학습목표**  
행(row)과 열(column)의 개념을 이해한다.

**문제**  
학생 3명의 이름, 나이, 점수를 딕셔너리로 만들고 출력하세요. 딕셔너리의 key는 컬럼명으로 사용될 예정입니다.

**힌트**  
`name`, `age`, `score`를 key로 만들고 각각 리스트 값을 넣으세요.

In [ ]:
students = {
    # 여기에 작성하세요.
}

print(students)

### 문제 5. (초급) 분석 질문 만들기

**학습목표**  
데이터 분석에서 질문 설정의 중요성을 이해한다.

**문제**  
학생 점수 데이터가 있다고 가정하고, 분석할 수 있는 질문 3개를 리스트로 작성하세요.

**힌트**  
예: 평균 점수는 얼마인가? 가장 높은 점수를 받은 학생은 누구인가?

In [ ]:
questions = [
    # 분석 질문 3개를 작성하세요.
]

for q in questions:
    print(q)

---
## Part 2. NumPy 기초


### 문제 6. (초급) NumPy 배열 생성

**학습목표**  
np.array()로 리스트를 ndarray로 변환한다.

**문제**  
리스트 `[10, 20, 30, 40, 50]`을 NumPy 배열로 만들고, 값과 타입을 출력하세요.

**힌트**  
`np.array()`를 사용하세요.

In [4]:
import numpy as np

# 여기에 코드를 작성하세요.
num_list = np.array([10, 20, 30, 40, 50])
print(num_list)
print(num_list.dtype)

[10 20 30 40 50]
int32


### 문제 7. (초급) 배열의 기본 속성 확인

**학습목표**  
shape, ndim, size, dtype을 확인한다.

**문제**  
2차원 배열을 만들고 `shape`, `ndim`, `size`, `dtype`을 출력하세요.

**힌트**  
`np.array([[1,2,3],[4,5,6]])`를 사용해보세요.

In [5]:
import numpy as np

# 여기에 코드를 작성하세요.
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.dtype)

(2, 3)
2
6
int32


### 문제 8. (초급) arange로 배열 만들기

**학습목표**  
연속된 숫자 배열을 생성한다.

**문제**  
0부터 9까지의 숫자를 가진 배열을 `np.arange()`로 만들고 출력하세요.

**힌트**  
range와 비슷하지만 NumPy 배열을 반환합니다.

In [6]:
import numpy as np

# 여기에 코드를 작성하세요.
nums = np.arange(10)
print(nums)

[0 1 2 3 4 5 6 7 8 9]


### 문제 9. (초급) reshape로 배열 모양 바꾸기

**학습목표**  
1차원 배열을 2차원 배열로 변환한다.

**문제**  
0부터 11까지의 숫자를 가진 배열을 만들고, 3행 4열 형태로 바꾸세요.

**힌트**  
원소 개수 12개는 3 x 4로 바꿀 수 있습니다.

In [7]:
import numpy as np

# 여기에 코드를 작성하세요.
nums = np.arange(12)
print(nums.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 문제 10. (초급) zeros와 ones

**학습목표**  
특정 값으로 채워진 배열을 만든다.

**문제**  
0으로 채워진 2행 3열 배열과 1로 채워진 3행 2열 배열을 각각 만드세요.

**힌트**  
`np.zeros()`와 `np.ones()`를 사용하세요.

In [9]:
import numpy as np

# 여기에 코드를 작성하세요.
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### 문제 11. (초급) linspace 사용하기

**학습목표**  
구간을 균등하게 나눈 배열을 만든다.

**문제**  
0부터 1까지를 5등분한 값을 `np.linspace()`로 생성하세요.

**힌트**  
시작값, 끝값, 개수를 차례대로 넣습니다.

In [10]:
import numpy as np

# 여기에 코드를 작성하세요.
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


### 문제 12. (중급) 배열 인덱싱

**학습목표**  
NumPy 배열에서 특정 원소를 선택한다.

**문제**  
2차원 배열에서 1행 2열 위치의 값을 출력하세요. 단, 파이썬 인덱스 기준으로 접근하세요.

**힌트**  
파이썬 인덱스는 0부터 시작합니다. `arr[행, 열]` 형식을 사용하세요.

In [11]:
import numpy as np

# 여기에 코드를 작성하세요.
nums = np.arange(12)
shaped = np.reshape(nums, (3, 4))

print(shaped[1][2])

6


### 문제 13. (중급) 배열 슬라이싱

**학습목표**  
NumPy 배열에서 일부 구간을 추출한다.

**문제**  
아래 배열에서 첫 번째 행 전체와 두 번째 열 전체를 각각 출력하세요.

**힌트**  
행 전체는 `arr[0, :]`, 열 전체는 `arr[:, 1]` 형식을 사용합니다.

In [13]:
import numpy as np

# 여기에 코드를 작성하세요.
print(shaped[0, :])
print(shaped[:, 1])

[0 1 2 3]
[1 5 9]


### 문제 14. (중급) 배열 연산

**학습목표**  
배열에 숫자를 더하고 곱한다.

**문제**  
배열 `[1, 2, 3, 4]`에 10을 더한 결과와 2를 곱한 결과를 각각 출력하세요.

**힌트**  
NumPy 배열은 반복문 없이 한 번에 연산할 수 있습니다.

In [14]:
import numpy as np

# 여기에 코드를 작성하세요.
nums2 = np.array([1, 2, 3, 4])

print(nums2 + 10)
print(nums2 * 2)

[11 12 13 14]
[2 4 6 8]


### 문제 15. (중급) 기본 통계 함수

**학습목표**  
배열의 합계, 평균, 최댓값, 최솟값을 구한다.

**문제**  
배열 `[80, 90, 75, 88, 92]`의 합계, 평균, 최댓값, 최솟값을 출력하세요.

**힌트**  
`sum()`, `mean()`, `max()`, `min()`을 사용하세요.

In [17]:
import numpy as np

# 여기에 코드를 작성하세요.
arr = np.array([80, 90, 75, 88, 92])

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

425
85.0
92
75


---
## Part 3. Pandas 기초


### 문제 16. (초급) Series 생성

**학습목표**  
Pandas Series를 만든다.

**문제**  
과일 이름 3개를 가진 Series를 만들고 출력하세요.

**힌트**  
`pd.Series()`를 사용하세요.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 17. (초급) DataFrame 생성

**학습목표**  
딕셔너리로 DataFrame을 만든다.

**문제**  
이름, 나이, 점수 컬럼을 가진 DataFrame을 생성하고 출력하세요.

**힌트**  
딕셔너리의 key가 컬럼명이 됩니다.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 18. (초급) head와 tail

**학습목표**  
데이터의 앞부분과 뒷부분을 확인한다.

**문제**  
DataFrame의 앞 3개 행과 뒤 2개 행을 출력하세요.

**힌트**  
`head(3)`, `tail(2)`를 사용하세요.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 19. (초급) shape와 columns

**학습목표**  
DataFrame의 크기와 컬럼명을 확인한다.

**문제**  
DataFrame의 행/열 개수와 컬럼명을 출력하세요.

**힌트**  
`df.shape`, `df.columns`를 사용하세요.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 20. (초급) info와 describe

**학습목표**  
DataFrame의 요약 정보를 확인한다.

**문제**  
DataFrame의 기본 정보와 통계 요약을 출력하세요.

**힌트**  
`info()`와 `describe()`를 사용하세요.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 21. (중급) 컬럼 선택

**학습목표**  
DataFrame에서 특정 컬럼을 선택한다.

**문제**  
DataFrame에서 `score` 컬럼만 선택하여 출력하세요.

**힌트**  
대괄호 안에 컬럼명을 문자열로 넣습니다.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 22. (중급) 여러 컬럼 선택

**학습목표**  
DataFrame에서 여러 컬럼을 선택한다.

**문제**  
DataFrame에서 `name`과 `score` 컬럼만 선택하여 출력하세요.

**힌트**  
여러 컬럼을 선택할 때는 리스트를 한 번 더 사용합니다.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 23. (중급) 새 컬럼 추가

**학습목표**  
기존 컬럼을 이용해 새 컬럼을 만든다.

**문제**  
점수에 5점을 더한 `bonus_score` 컬럼을 새로 만드세요.

**힌트**  
`df['새컬럼'] = ...` 형식을 사용하세요.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 24. (중급) CSV 저장과 읽기

**학습목표**  
DataFrame을 CSV로 저장하고 다시 읽는다.

**문제**  
DataFrame을 `students.csv`로 저장한 뒤 다시 읽어서 출력하세요.

**힌트**  
저장할 때 `index=False`를 사용하면 인덱스가 파일에 저장되지 않습니다.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


### 문제 25. (중급) 간단한 조건 컬럼 만들기

**학습목표**  
조건에 따라 합격 여부를 만든다.

**문제**  
score가 80점 이상이면 True, 아니면 False가 되는 `pass` 컬럼을 만드세요.

**힌트**  
비교 연산 결과는 True/False 값이 됩니다.

In [ ]:
import pandas as pd

# 여기에 코드를 작성하세요.


---
## Part 4. ⭐ 심화: ndarray 심화


### 문제 26. (심화) Boolean Indexing

**학습목표**  
조건을 만족하는 배열 값만 추출한다.

**문제**  
배열 `[10, 25, 30, 45, 50]`에서 30 이상인 값만 추출하세요.

**힌트**  
조건식을 먼저 만들고 그 조건을 배열에 적용합니다.

In [ ]:
# 필요한 라이브러리를 import하고 코드를 작성하세요.


### 문제 27. (심화) Fancy Indexing

**학습목표**  
인덱스 배열로 원하는 위치의 값을 선택한다.

**문제**  
배열 `[100, 200, 300, 400, 500]`에서 0번, 2번, 4번 위치의 값을 한 번에 선택하세요.

**힌트**  
인덱스 목록을 리스트로 전달합니다.

In [ ]:
# 필요한 라이브러리를 import하고 코드를 작성하세요.


### 문제 28. (심화) Broadcasting 이해

**학습목표**  
크기가 다른 배열 간 연산을 이해한다.

**문제**  
2행 3열 배열에 `[10, 20, 30]` 배열을 더한 결과를 출력하세요.

**힌트**  
열 개수가 같기 때문에 각 행에 같은 값이 더해집니다.

In [ ]:
# 필요한 라이브러리를 import하고 코드를 작성하세요.


---
## Part 5. ⭐ 심화: 벡터 연산


### 문제 29. (심화) 두 벡터의 합과 차

**학습목표**  
벡터 간 기본 연산을 수행한다.

**문제**  
벡터 a=[1,2,3], b=[4,5,6]의 합과 차를 출력하세요.

**힌트**  
NumPy 배열끼리 `+`, `-` 연산을 사용합니다.

In [ ]:
# 필요한 라이브러리를 import하고 코드를 작성하세요.


### 문제 30. (심화) Dot Product

**학습목표**  
두 벡터의 내적을 계산한다.

**문제**  
벡터 a=[1,2,3], b=[4,5,6]의 내적을 구하세요.

**힌트**  
`np.dot(a, b)` 또는 `a @ b`를 사용할 수 있습니다.

In [ ]:
# 필요한 라이브러리를 import하고 코드를 작성하세요.
